layout_spectrum: 0.6866442
typography_spectrum: 0.2126296
color:
  lightness: 0.214017
  brandStrength: 0.825347
  saturation: 0.9620792
  rhythmicContrast: 0.4847702
  brandColors:
    - '#FDFDFD'
    - '#D7261F'
    - '#FFBDBD'
    - '#040231'
    - '#9189AB'
name: hongkonglish
